// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WINNERLib/quotation_msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "WINNERLib/quotation_msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_WINNERLib_2fquotation_5fmsg_2eproto() {
  delete QuotationRequest::default_instance_;
  delete QuotationMessage::default_instance_;
  delete QuotationMessage_QuotationFillMessage::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::protobuf_AddDesc_TLib_2fcore_2ftsystem_5ftime_2eproto();
  ::protobuf_AddDesc_TLib_2fcore_2ftsystem_5freturn_5fcode_2eproto();
  ::protobuf_AddDesc_TLib_2ftool_2ftsystem_5frational_5fnumber_2eproto();
  QuotationRequest::default_instance_ = new QuotationRequest();
  QuotationMessage::default_instance_ = new QuotationMessage();
  QuotationMessage_QuotationFillMessage::default_instance_ = new QuotationMessage_QuotationFillMessage();
  QuotationRequest::default_instance_->InitAsDefaultInstance();
  QuotationMessage::default_instance_->InitAsDefaultInstance();
  QuotationMessage_QuotationFillMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_WINNERLib_2fquotation_5fmsg_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto_once_);
void protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto_once_,
                 &protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_WINNERLib_2fquotation_5fmsg_2eproto {
  StaticDescriptorInitializer_WINNERLib_2fquotation_5fmsg_2eproto() {
    protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto();
  }
} static_descriptor_initializer_WINNERLib_2fquotation_5fmsg_2eproto_;
#endif
bool QuotationReqType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int QuotationRequest::kReqTypeFieldNumber;
const int QuotationRequest::kCodeFieldNumber;
const int QuotationRequest::kBegTimeFieldNumber;
const int QuotationRequest::kEndTimeFieldNumber;
#endif  // !_MSC_VER

QuotationRequest::QuotationRequest()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void QuotationRequest::InitAsDefaultInstance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  beg_time_ = const_cast< ::Time*>(
      ::Time::internal_default_instance());
#else
  beg_time_ = const_cast< ::Time*>(&::Time::default_instance());
#endif
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  end_time_ = const_cast< ::Time*>(
      ::Time::internal_default_instance());
#else
  end_time_ = const_cast< ::Time*>(&::Time::default_instance());
#endif
}

QuotationRequest::QuotationRequest(const QuotationRequest& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void QuotationRequest::SharedCtor() {
  _cached_size_ = 0;
  req_type_ = 0;
  code_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  beg_time_ = NULL;
  end_time_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

QuotationRequest::~QuotationRequest() {
  SharedDtor();
}

void QuotationRequest::SharedDtor() {
  if (code_ != &::google::protobuf::internal::kEmptyString) {
    delete code_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete beg_time_;
    delete end_time_;
  }
}

void QuotationRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const QuotationRequest& QuotationRequest::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto();
#endif
  return *default_instance_;
}

QuotationRequest* QuotationRequest::default_instance_ = NULL;

QuotationRequest* QuotationRequest::New() const {
  return new QuotationRequest;
}

void QuotationRequest::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    req_type_ = 0;
    if (has_code()) {
      if (code_ != &::google::protobuf::internal::kEmptyString) {
        code_->clear();
      }
    }
    if (has_beg_time()) {
      if (beg_time_ != NULL) beg_time_->::Time::Clear();
    }
    if (has_end_time()) {
      if (end_time_ != NULL) end_time_->::Time::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool QuotationRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .QuotationReqType req_type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::QuotationReqType_IsValid(value)) {
            set_req_type(static_cast< ::QuotationReqType >(value));
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_code;
        break;
      }

      // required string code = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_code:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_code()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_beg_time;
        break;
      }

      // required .Time beg_time = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_beg_time:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_beg_time()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_end_time;
        break;
      }

      // required .Time end_time = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_end_time:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_end_time()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void QuotationRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .QuotationReqType req_type = 1;
  if (has_req_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->req_type(), output);
  }

  // required string code = 2;
  if (has_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->code(), output);
  }

  // required .Time beg_time = 3;
  if (has_beg_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->beg_time(), output);
  }

  // required .Time end_time = 4;
  if (has_end_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->end_time(), output);
  }

}

int QuotationRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .QuotationReqType req_type = 1;
    if (has_req_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->req_type());
    }

    // required string code = 2;
    if (has_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->code());
    }

    // required .Time beg_time = 3;
    if (has_beg_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->beg_time());
    }

    // required .Time end_time = 4;
    if (has_end_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->end_time());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void QuotationRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const QuotationRequest*>(&from));
}

void QuotationRequest::MergeFrom(const QuotationRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_req_type()) {
      set_req_type(from.req_type());
    }
    if (from.has_code()) {
      set_code(from.code());
    }
    if (from.has_beg_time()) {
      mutable_beg_time()->::Time::MergeFrom(from.beg_time());
    }
    if (from.has_end_time()) {
      mutable_end_time()->::Time::MergeFrom(from.end_time());
    }
  }
}

void QuotationRequest::CopyFrom(const QuotationRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QuotationRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void QuotationRequest::Swap(QuotationRequest* other) {
  if (other != this) {
    std::swap(req_type_, other->req_type_);
    std::swap(code_, other->code_);
    std::swap(beg_time_, other->beg_time_);
    std::swap(end_time_, other->end_time_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string QuotationRequest::GetTypeName() const {
  return "QuotationRequest";
}


// ===================================================================

#ifndef _MSC_VER
const int QuotationMessage_QuotationFillMessage::kTimeFieldNumber;
const int QuotationMessage_QuotationFillMessage::kPriceFieldNumber;
const int QuotationMessage_QuotationFillMessage::kVolFieldNumber;
const int QuotationMessage_QuotationFillMessage::kPriceChangeFieldNumber;
const int QuotationMessage_QuotationFillMessage::kIsChangePositiveFieldNumber;
#endif  // !_MSC_VER

QuotationMessage_QuotationFillMessage::QuotationMessage_QuotationFillMessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void QuotationMessage_QuotationFillMessage::InitAsDefaultInstance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  time_ = const_cast< ::Time*>(
      ::Time::internal_default_instance());
#else
  time_ = const_cast< ::Time*>(&::Time::default_instance());
#endif
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  price_ = const_cast< ::RationalNumber*>(
      ::RationalNumber::internal_default_instance());
#else
  price_ = const_cast< ::RationalNumber*>(&::RationalNumber::default_instance());
#endif
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  price_change_ = const_cast< ::RationalNumber*>(
      ::RationalNumber::internal_default_instance());
#else
  price_change_ = const_cast< ::RationalNumber*>(&::RationalNumber::default_instance());
#endif
}

QuotationMessage_QuotationFillMessage::QuotationMessage_QuotationFillMessage(const QuotationMessage_QuotationFillMessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void QuotationMessage_QuotationFillMessage::SharedCtor() {
  _cached_size_ = 0;
  time_ = NULL;
  price_ = NULL;
  vol_ = 0u;
  price_change_ = NULL;
  is_change_positive_ = true;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

QuotationMessage_QuotationFillMessage::~QuotationMessage_QuotationFillMessage() {
  SharedDtor();
}

void QuotationMessage_QuotationFillMessage::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete time_;
    delete price_;
    delete price_change_;
  }
}

void QuotationMessage_QuotationFillMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const QuotationMessage_QuotationFillMessage& QuotationMessage_QuotationFillMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto();
#endif
  return *default_instance_;
}

QuotationMessage_QuotationFillMessage* QuotationMessage_QuotationFillMessage::default_instance_ = NULL;

QuotationMessage_QuotationFillMessage* QuotationMessage_QuotationFillMessage::New() const {
  return new QuotationMessage_QuotationFillMessage;
}

void QuotationMessage_QuotationFillMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_time()) {
      if (time_ != NULL) time_->::Time::Clear();
    }
    if (has_price()) {
      if (price_ != NULL) price_->::RationalNumber::Clear();
    }
    vol_ = 0u;
    if (has_price_change()) {
      if (price_change_ != NULL) price_change_->::RationalNumber::Clear();
    }
    is_change_positive_ = true;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool QuotationMessage_QuotationFillMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .Time time = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_time()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_price;
        break;
      }

      // required .RationalNumber price = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_price:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_price()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_vol;
        break;
      }

      // required uint32 vol = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_vol:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &vol_)));
          set_has_vol();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_price_change;
        break;
      }

      // optional .RationalNumber price_change = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_price_change:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_price_change()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_is_change_positive;
        break;
      }

      // optional bool is_change_positive = 5 [default = true];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_is_change_positive:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_change_positive_)));
          set_has_is_change_positive();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void QuotationMessage_QuotationFillMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .Time time = 1;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->time(), output);
  }

  // required .RationalNumber price = 2;
  if (has_price()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->price(), output);
  }

  // required uint32 vol = 3;
  if (has_vol()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->vol(), output);
  }

  // optional .RationalNumber price_change = 4;
  if (has_price_change()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->price_change(), output);
  }

  // optional bool is_change_positive = 5 [default = true];
  if (has_is_change_positive()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->is_change_positive(), output);
  }

}

int QuotationMessage_QuotationFillMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .Time time = 1;
    if (has_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->time());
    }

    // required .RationalNumber price = 2;
    if (has_price()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->price());
    }

    // required uint32 vol = 3;
    if (has_vol()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->vol());
    }

    // optional .RationalNumber price_change = 4;
    if (has_price_change()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->price_change());
    }

    // optional bool is_change_positive = 5 [default = true];
    if (has_is_change_positive()) {
      total_size += 1 + 1;
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void QuotationMessage_QuotationFillMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const QuotationMessage_QuotationFillMessage*>(&from));
}

void QuotationMessage_QuotationFillMessage::MergeFrom(const QuotationMessage_QuotationFillMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_time()) {
      mutable_time()->::Time::MergeFrom(from.time());
    }
    if (from.has_price()) {
      mutable_price()->::RationalNumber::MergeFrom(from.price());
    }
    if (from.has_vol()) {
      set_vol(from.vol());
    }
    if (from.has_price_change()) {
      mutable_price_change()->::RationalNumber::MergeFrom(from.price_change());
    }
    if (from.has_is_change_positive()) {
      set_is_change_positive(from.is_change_positive());
    }
  }
}

void QuotationMessage_QuotationFillMessage::CopyFrom(const QuotationMessage_QuotationFillMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QuotationMessage_QuotationFillMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (has_price()) {
    if (!this->price().IsInitialized()) return false;
  }
  if (has_price_change()) {
    if (!this->price_change().IsInitialized()) return false;
  }
  return true;
}

void QuotationMessage_QuotationFillMessage::Swap(QuotationMessage_QuotationFillMessage* other) {
  if (other != this) {
    std::swap(time_, other->time_);
    std::swap(price_, other->price_);
    std::swap(vol_, other->vol_);
    std::swap(price_change_, other->price_change_);
    std::swap(is_change_positive_, other->is_change_positive_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string QuotationMessage_QuotationFillMessage::GetTypeName() const {
  return "QuotationMessage.QuotationFillMessage";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int QuotationMessage::kCodeFieldNumber;
const int QuotationMessage::kQuoteFillMsgFieldNumber;
#endif  // !_MSC_VER

QuotationMessage::QuotationMessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void QuotationMessage::InitAsDefaultInstance() {
}

QuotationMessage::QuotationMessage(const QuotationMessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void QuotationMessage::SharedCtor() {
  _cached_size_ = 0;
  code_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

QuotationMessage::~QuotationMessage() {
  SharedDtor();
}

void QuotationMessage::SharedDtor() {
  if (code_ != &::google::protobuf::internal::kEmptyString) {
    delete code_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void QuotationMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const QuotationMessage& QuotationMessage::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_WINNERLib_2fquotation_5fmsg_2eproto();
#endif
  return *default_instance_;
}

QuotationMessage* QuotationMessage::default_instance_ = NULL;

QuotationMessage* QuotationMessage::New() const {
  return new QuotationMessage;
}

void QuotationMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_code()) {
      if (code_ != &::google::protobuf::internal::kEmptyString) {
        code_->clear();
      }
    }
  }
  quote_fill_msg_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool QuotationMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string code = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_code()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_quote_fill_msg;
        break;
      }

      // repeated .QuotationMessage.QuotationFillMessage quote_fill_msg = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_quote_fill_msg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_quote_fill_msg()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_quote_fill_msg;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void QuotationMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string code = 1;
  if (has_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->code(), output);
  }

  // repeated .QuotationMessage.QuotationFillMessage quote_fill_msg = 2;
  for (int i = 0; i < this->quote_fill_msg_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->quote_fill_msg(i), output);
  }

}

int QuotationMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string code = 1;
    if (has_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->code());
    }

  }
  // repeated .QuotationMessage.QuotationFillMessage quote_fill_msg = 2;
  total_size += 1 * this->quote_fill_msg_size();
  for (int i = 0; i < this->quote_fill_msg_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->quote_fill_msg(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void QuotationMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const QuotationMessage*>(&from));
}

void QuotationMessage::MergeFrom(const QuotationMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  quote_fill_msg_.MergeFrom(from.quote_fill_msg_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_code()) {
      set_code(from.code());
    }
  }
}

void QuotationMessage::CopyFrom(const QuotationMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QuotationMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < quote_fill_msg_size(); i++) {
    if (!this->quote_fill_msg(i).IsInitialized()) return false;
  }
  return true;
}

void QuotationMessage::Swap(QuotationMessage* other) {
  if (other != this) {
    std::swap(code_, other->code_);
    quote_fill_msg_.Swap(&other->quote_fill_msg_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string QuotationMessage::GetTypeName() const {
  return "QuotationMessage";
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
